/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Address;
import Model.Person;
import Model.Contact;
import javax.swing.JOptionPane;

/**
 *
 * @author pulkit
 */
public class HuskyCardJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private Person person;
    public HuskyCardJFrame() {
        initComponents();
        this.person = new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        lastName = new javax.swing.JLabel();
        lastNameText = new javax.swing.JTextField();
        displayButton = new javax.swing.JButton();
        street = new javax.swing.JLabel();
        streetText = new javax.swing.JTextField();
        nuid = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        collegeName = new javax.swing.JLabel();
        nuidText = new javax.swing.JTextField();
        firstNameText = new javax.swing.JTextField();
        collegeNameText = new javax.swing.JTextField();
        phoneOff = new javax.swing.JLabel();
        phonePer = new javax.swing.JLabel();
        emailOff = new javax.swing.JLabel();
        emailPer = new javax.swing.JLabel();
        apt = new javax.swing.JLabel();
        cityState = new javax.swing.JLabel();
        zipCode = new javax.swing.JLabel();
        phoneOffText = new javax.swing.JTextField();
        phonePerText = new javax.swing.JTextField();
        emailOffText = new javax.swing.JTextField();
        emailPerText = new javax.swing.JTextField();
        aptText = new javax.swing.JTextField();
        cityStateText = new javax.swing.JTextField();
        zipCodeText = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        nuidDisplay = new javax.swing.JTextField();
        firstNameDisplay = new javax.swing.JTextField();
        lastNameDisplay = new javax.swing.JTextField();
        collegeNameDisplay = new javax.swing.JTextField();
        phoneOffDisplay = new javax.swing.JTextField();
        phonePerDisplay = new javax.swing.JTextField();
        emailOffDisplay = new javax.swing.JTextField();
        emailPerDisplay = new javax.swing.JTextField();
        streetDisplay = new javax.swing.JTextField();
        aptDisplay = new javax.swing.JTextField();
        cityStateDisplay = new javax.swing.JTextField();
        zipCodeDisplay = new javax.swing.JTextField();
        nuid1 = new javax.swing.JLabel();
        firstName1 = new javax.swing.JLabel();
        lastName1 = new javax.swing.JLabel();
        collegeName1 = new javax.swing.JLabel();
        phoneOff1 = new javax.swing.JLabel();
        phonePer1 = new javax.swing.JLabel();
        emailOff1 = new javax.swing.JLabel();
        emailPer1 = new javax.swing.JLabel();
        street1 = new javax.swing.JLabel();
        apt1 = new javax.swing.JLabel();
        cityState1 = new javax.swing.JLabel();
        zipCode1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lastName.setText("LastName");

        displayButton.setText("Display");
        displayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayButtonActionPerformed(evt);
            }
        });

        street.setText("Street");

        nuid.setText("NUID");

        firstName.setText("FirstName");

        collegeName.setText("CollegeName");

        nuidText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuidTextActionPerformed(evt);
            }
        });

        firstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextActionPerformed(evt);
            }
        });

        phoneOff.setText("Phone(Off)");

        phonePer.setText("Phone(Per)");

        emailOff.setText("Email(Off)");

        emailPer.setText("Email(Per)");

        apt.setText("Apt");

        cityState.setText("City/State");

        zipCode.setText("ZipCode");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstName)
                                    .addComponent(nuid))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nuidText, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(firstNameText)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phonePer)
                                    .addComponent(collegeName)
                                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phoneOffText, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(collegeNameText)
                                    .addComponent(phonePerText)
                                    .addComponent(lastNameText, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emailPerText, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(emailOffText)
                                                .addComponent(streetText)
                                                .addComponent(cityStateText)
                                                .addComponent(aptText)
                                                .addComponent(zipCodeText, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))
                                        .addGap(0, 1, Short.MAX_VALUE)))))
                        .addGap(65, 65, 65))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailPer)
                            .addComponent(cityState)
                            .addComponent(apt)
                            .addComponent(street)
                            .addComponent(emailOff))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneOff)
                            .addComponent(zipCode)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(displayButton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuid)
                    .addComponent(nuidText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstName)
                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastName)
                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(collegeName)
                    .addComponent(collegeNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneOff)
                    .addComponent(phoneOffText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phonePerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonePer))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailOff, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailOffText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailPer)
                    .addComponent(emailPerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(street)
                    .addComponent(streetText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(apt)
                    .addComponent(aptText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityState)
                    .addComponent(cityStateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipCode)
                    .addComponent(zipCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(displayButton))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        firstNameDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameDisplayActionPerformed(evt);
            }
        });

        zipCodeDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipCodeDisplayActionPerformed(evt);
            }
        });

        nuid1.setText("NUID");

        firstName1.setText("FirstName");

        lastName1.setText("LastName");

        collegeName1.setText("CollegeName");

        phoneOff1.setText("Phone(Off)");

        phonePer1.setText("Phone(Per)");

        emailOff1.setText("Email(Off)");

        emailPer1.setText("Email(Per)");

        street1.setText("Street");

        apt1.setText("Apt");

        cityState1.setText("City/State");

        zipCode1.setText("ZipCode");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zipCode1)
                    .addComponent(firstName1)
                    .addComponent(nuid1)
                    .addComponent(lastName1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(collegeName1)
                    .addComponent(phoneOff1)
                    .addComponent(emailOff1)
                    .addComponent(phonePer1)
                    .addComponent(emailPer1)
                    .addComponent(street1)
                    .addComponent(cityState1)
                    .addComponent(apt1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(firstNameDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addComponent(nuidDisplay)
                        .addComponent(lastNameDisplay)
                        .addComponent(collegeNameDisplay)
                        .addComponent(phoneOffDisplay)
                        .addComponent(phonePerDisplay)
                        .addComponent(emailOffDisplay)
                        .addComponent(streetDisplay)
                        .addComponent(cityStateDisplay))
                    .addComponent(zipCodeDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aptDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailPerDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuidDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuid1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstName1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lastNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lastName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(collegeNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(collegeName1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneOffDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneOff1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phonePerDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonePer1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailOffDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailOff1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailPer1)
                    .addComponent(emailPerDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(streetDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(street1))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apt1)
                    .addComponent(aptDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityState1)
                    .addComponent(cityStateDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipCode1)
                    .addComponent(zipCodeDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayButtonActionPerformed
        String nuid = nuidText.getText();
        String firstName = firstNameText.getText();
        String lastName = lastNameText.getText();
        String collegeName = collegeNameText.getText();
        String phoneOff = phoneOffText.getText();
        String phonePer = phonePerText.getText();
        String emailOff = emailOffText.getText();
        String emailPer = emailPerText.getText();
        String street = streetText.getText();
        String apt = aptText.getText();
        String cityState = cityStateText.getText();
        String zipCode = zipCodeText.getText();
        this.person.setNuid(nuid);
        this.person.setFirstName(firstName);
        this.person.setLastName(lastName);
        this.person.setCollegeName(collegeName);
//        this.person.setPhoneOff(phoneOff);
//        this.person.setPhonePer(phonePer);
//        this.person.setEmailOff(emailOff);
//        this.person.setEmailPer(emailPer);
        
        Address addressOfPerson = this.person.getAddress();
        addressOfPerson.setStreet(street);
        addressOfPerson.setApt(apt);        
        addressOfPerson.setCityState(cityState);
        addressOfPerson.setZipCode(zipCode);
        
        Contact personalContact = this.person.getPersonalContact();
        personalContact.setEmail(emailPer);
        personalContact.setPhone(phonePer);
        
        Contact officeContact = this.person.getOfficeContact();
        officeContact.setEmail(emailOff);
        officeContact.setPhone(phoneOff);
        //JOptionPane.showMessageDialog(null, "SAVED SUCCESSFULLY!");
        
        display();
    }//GEN-LAST:event_displayButtonActionPerformed

    private void firstNameDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameDisplayActionPerformed

    private void nuidTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuidTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuidTextActionPerformed

    private void zipCodeDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipCodeDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipCodeDisplayActionPerformed

    private void firstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextActionPerformed

    private void display(){
        if(this.person.getNuid().isEmpty()
           || this.person.getFirstName().isEmpty()
           || this.person.getLastName().isEmpty()
           || this.person.getCollegeName().isEmpty()
           || this.person.getOfficeContact().getPhone().isEmpty()
           || this.person.getPersonalContact().getPhone().isEmpty()
           || this.person.getOfficeContact().getEmail().isEmpty()
           || this.person.getPersonalContact().getEmail().isEmpty()
           || this.person.getAddress().getStreet().isEmpty()
           || this.person.getAddress().getApt().isEmpty()
           || this.person.getAddress().getCityState().isEmpty()
           || this.person.getAddress().getZipCode().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Please enter all values!!");}
        else{
        nuidDisplay.setText(this.person.getNuid());
        firstNameDisplay.setText(this.person.getFirstName());
        lastNameDisplay.setText(this.person.getLastName());
        collegeNameDisplay.setText(this.person.getCollegeName());
        phoneOffDisplay.setText(this.person.getOfficeContact().getPhone());
        phonePerDisplay.setText(this.person.getPersonalContact().getPhone());
        emailOffDisplay.setText(this.person.getOfficeContact().getEmail());
        emailPerDisplay.setText(this.person.getPersonalContact().getEmail());
        streetDisplay.setText(this.person.getAddress().getStreet());
        aptDisplay.setText(this.person.getAddress().getApt());
        cityStateDisplay.setText(this.person.getAddress().getCityState());
        zipCodeDisplay.setText(this.person.getAddress().getZipCode());}
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HuskyCardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HuskyCardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HuskyCardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HuskyCardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HuskyCardJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apt;
    private javax.swing.JLabel apt1;
    private javax.swing.JTextField aptDisplay;
    private javax.swing.JTextField aptText;
    private javax.swing.JLabel cityState;
    private javax.swing.JLabel cityState1;
    private javax.swing.JTextField cityStateDisplay;
    private javax.swing.JTextField cityStateText;
    private javax.swing.JLabel collegeName;
    private javax.swing.JLabel collegeName1;
    private javax.swing.JTextField collegeNameDisplay;
    private javax.swing.JTextField collegeNameText;
    private javax.swing.JButton displayButton;
    private javax.swing.JLabel emailOff;
    private javax.swing.JLabel emailOff1;
    private javax.swing.JTextField emailOffDisplay;
    private javax.swing.JTextField emailOffText;
    private javax.swing.JLabel emailPer;
    private javax.swing.JLabel emailPer1;
    private javax.swing.JTextField emailPerDisplay;
    private javax.swing.JTextField emailPerText;
    private javax.swing.JLabel firstName;
    private javax.swing.JLabel firstName1;
    private javax.swing.JTextField firstNameDisplay;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lastName;
    private javax.swing.JLabel lastName1;
    private javax.swing.JTextField lastNameDisplay;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JLabel nuid;
    private javax.swing.JLabel nuid1;
    private javax.swing.JTextField nuidDisplay;
    private javax.swing.JTextField nuidText;
    private javax.swing.JLabel phoneOff;
    private javax.swing.JLabel phoneOff1;
    private javax.swing.JTextField phoneOffDisplay;
    private javax.swing.JTextField phoneOffText;
    private javax.swing.JLabel phonePer;
    private javax.swing.JLabel phonePer1;
    private javax.swing.JTextField phonePerDisplay;
    private javax.swing.JTextField phonePerText;
    private javax.swing.JLabel street;
    private javax.swing.JLabel street1;
    private javax.swing.JTextField streetDisplay;
    private javax.swing.JTextField streetText;
    private javax.swing.JLabel zipCode;
    private javax.swing.JLabel zipCode1;
    private javax.swing.JTextField zipCodeDisplay;
    private javax.swing.JTextField zipCodeText;
    // End of variables declaration//GEN-END:variables
}
